name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up QEMU to emulate different CPU architectures
      - name: Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v2

      # Step 3: Set up Docker Buildx for building multi-architecture images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Log in to Quay.io using GitHub Secrets
      - name: Log in to Quay.io
        run: echo "${{ secrets.QUAY_PASSWORD }}" | docker login quay.io -u "${{ secrets.QUAY_USERNAME }}" --password-stdin

      # Step 5: Build and push the multi-architecture image to Quay.io
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: quay.io/"${{ secrets.QUAY_USERNAME }}"/multi-arch-python-app:latest
          platforms: linux/amd64,linux/arm64
